name: Deploy Site Pages

on:
  push:
    branches: [v4]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - uses: pnpm/action-setup@v4 # pnpm is optional but recommended, you can also use npm / yarn
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: ''

      - name: Setup pnpm
        run: npm install -g pnpm
          
      - name: Setup Pages
        run: |
          pnpm install

      # - name: i18n Translate(currently only English)
      #   run: |
      #     pnpm run i18n:translate

      - name: Build with
        run: |
          pnpm run build
          
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4 # 一个自动发布github pages的action
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }} 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
          external_repository: dodolalorc/dodolalorc.github.io # 发布到哪个repo
          personal_token: ${{ secrets.ACTION_ACCESS_TOKEN }} # 发布到其他repo需要提供上面生成的personal access token
          publish_dir: ./public/ # 要发布哪个文件夹的内容
          keep_files: false # 是否保留其他文件
          publish_branch: main # 发布到哪个branch
          commit_message: ${{ github.event.head_commit.message }} # 提交信息
      
      - name: Deploy to Remote Server
        uses: easingthemes/ssh-deploy@v5.1.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SOURCE: "public/"
